data["Core Java Fundamentals"] = [

    {
    question: "What is Java?",
    answer: "Java is a high-level, object-oriented programming language developed by Sun Microsystems. It follows the principle of Write Once, Run Anywhere because Java code is compiled into bytecode which can run on any system having a JVM."
    },
    
    {
    question: "Why is Java called platform independent?",
    answer: "Java source code is compiled into bytecode. This bytecode can run on any operating system that has a compatible JVM. Because the same bytecode works across multiple platforms without recompilation, Java is considered platform independent."
    },
    
    {
    question: "What is the difference between JDK, JRE and JVM?",
    answer: "JVM executes Java bytecode. JRE contains JVM plus runtime libraries required to run Java applications. JDK contains JRE along with development tools such as javac, javadoc and debugger required to develop Java applications."
    },
    
    {
    question: "What happens when you compile a Java program?",
    answer: "The Java compiler javac converts the .java source file into a .class file containing bytecode. This bytecode is later loaded and executed by the JVM."
    },
    
    {
    question: "What happens when you run a Java program?",
    answer: "The JVM loads the class, verifies the bytecode, allocates memory, initializes classes, and then starts execution from the main method. The bytecode may also be converted into machine code by the JIT compiler for better performance."
    },
    
    {
    question: "What is JVM?",
    answer: "JVM stands for Java Virtual Machine. It is a runtime engine responsible for loading, verifying and executing Java bytecode. It provides memory management, garbage collection and platform independence."
    },
    
    {
    question: "What is bytecode?",
    answer: "Bytecode is an intermediate instruction set generated by the Java compiler. It is not machine-specific and can be executed by any JVM regardless of the underlying operating system."
    },
    
    {
    question: "What is JIT Compiler?",
    answer: "JIT stands for Just-In-Time Compiler. It identifies frequently executed code and converts bytecode into native machine code at runtime, improving application performance."
    },
    
    {
    question: "What is the main method signature in Java?",
    answer: "The standard main method signature is public static void main(String[] args). It serves as the entry point of a Java application."
    },
    
    {
    question: "Why is the main method static?",
    answer: "The JVM invokes the main method before creating any object. Since static methods belong to the class and not an object, the JVM can call the method directly."
    },
    
    {
    question: "Why is String[] args passed to the main method?",
    answer: "It allows command-line arguments to be passed to the application when it starts. Each argument is stored as an element of the String array."
    },
    
    {
    question: "Can we overload the main method?",
    answer: "Yes, the main method can be overloaded. However, the JVM will only invoke the method having the standard signature public static void main(String[] args)."
    },
    
    {
    question: "Can we override the main method?",
    answer: "No. The main method is static, and static methods are hidden rather than overridden."
    },
    
    {
    question: "What are Java keywords?",
    answer: "Keywords are reserved words in Java that have predefined meanings and cannot be used as identifiers. Examples include class, static, final, public and return."
    },
    
    {
    question: "What is an identifier in Java?",
    answer: "An identifier is the name used for classes, methods, variables or packages. It must follow Java naming rules and cannot be a reserved keyword."
    },
    
    {
    question: "What are primitive data types in Java?",
    answer: "Java provides eight primitive data types: byte, short, int, long, float, double, char and boolean."
    },
    
    {
    question: "What is the size of all primitive data types?",
    answer: "byte is 1 byte, short is 2 bytes, int is 4 bytes, long is 8 bytes, float is 4 bytes, double is 8 bytes, char is 2 bytes and boolean is JVM dependent though logically it stores true or false."
    },
    
    {
    question: "What is type casting in Java?",
    answer: "Type casting is the conversion of one data type into another. It can be implicit when converting smaller types to larger types or explicit when converting larger types to smaller types."
    },
    
    {
    question: "What is the difference between implicit and explicit casting?",
    answer: "Implicit casting is performed automatically when there is no risk of data loss. Explicit casting requires the programmer to specify the conversion because data loss may occur."
    },
    
    {
    question: "What are variables in Java?",
    answer: "Variables are named memory locations used to store data. Java supports local variables, instance variables and static variables."
    },
    
    {
    question: "Does Java support pass by reference?",
    answer: "No. Java is strictly pass by value. For primitive types, the actual value is copied. For objects, the reference value is copied, but the original reference itself is not passed."
    },
    
    {
    question: "Explain Java pass by value with objects.",
    answer: "When an object is passed to a method, a copy of the reference is passed. Both references point to the same object, so object state can be modified. However, reassigning the reference inside the method does not affect the original reference."
    },
    
    {
    question: "What is the final keyword in Java?",
    answer: "The final keyword is used to restrict modification. A final variable cannot be reassigned, a final method cannot be overridden, and a final class cannot be inherited."
    },
    
    {
    question: "What is the static keyword in Java?",
    answer: "The static keyword makes a member belong to the class rather than individual objects. Static members are created once and shared by all instances."
    },
    
    {
    question: "Can we access static members without creating an object?",
    answer: "Yes. Since static members belong to the class, they can be accessed using the class name without creating an object."
    },
    
    {
    question: "What is a static block?",
    answer: "A static block is executed only once when the class is loaded into memory. It is commonly used for static initialization."
    },
    
    {
    question: "What is a package in Java?",
    answer: "A package is a namespace used to organize related classes and interfaces. It helps avoid naming conflicts and improves code maintainability."
    },
    
    {
    question: "What are access modifiers in Java?",
    answer: "Access modifiers control visibility. Java provides private, default, protected and public access levels."
    },
    
    {
    question: "What is the difference between public, protected, default and private?",
    answer: "Public members are accessible everywhere. Protected members are accessible within the package and through inheritance. Default members are accessible only within the same package. Private members are accessible only within the same class."
    },
    
    {
    question: "What is class loading in Java?",
    answer: "Class loading is the process of loading class bytecode into JVM memory. It is performed by class loaders before the class can be used."
    },
    
    {
    question: "What are the different class loaders in Java?",
    answer: "Bootstrap ClassLoader loads core Java classes. Platform ClassLoader loads platform libraries. Application ClassLoader loads classes from the application classpath."
    },
    
    {
    question: "What is the difference between == and equals()?",
    answer: "The == operator compares memory references for objects, whereas equals() compares object content if it is overridden appropriately."
    },
    
    {
    question: "When should equals() be overridden?",
    answer: "equals() should be overridden when logical equality is required. For example, two Employee objects with the same employee ID may be considered equal even if they are different instances."
    },
    
    {
    question: "Why should hashCode() be overridden when equals() is overridden?",
    answer: "The Java contract states that equal objects must have the same hash code. Failing to override hashCode() can cause incorrect behavior in HashMap, HashSet and other hash-based collections."
    },
    
    {
    question: "What is the Object class?",
    answer: "Object is the root class of the Java class hierarchy. Every Java class directly or indirectly inherits from Object."
    },
    
    {
    question: "What are some important methods of Object class?",
    answer: "Important methods include equals(), hashCode(), toString(), clone(), getClass(), notify(), notifyAll() and wait()."
    },
    
    {
    question: "What is an immutable object?",
    answer: "An immutable object cannot be modified after creation. Once constructed, its state remains unchanged throughout its lifetime."
    },
    
    {
    question: "Why is String immutable?",
    answer: "String immutability improves security, thread safety, caching efficiency and reliability. It also enables String Pool optimization."
    },
    
    {
    question: "What is the difference between shallow copy and deep copy?",
    answer: "A shallow copy duplicates object references, so nested objects are shared. A deep copy creates completely independent copies of all nested objects."
    },
    
    {
    question: "What is a marker interface?",
    answer: "A marker interface does not contain methods or constants. It is used to provide metadata to the JVM or frameworks. Examples include Serializable and Cloneable."
    }
    
    ];